---
- name: Install the Elasticsearch User Agent Plugin
  become: yes
  hosts: all
  
  tasks:
  
  - shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch --silent ingest-user-agent
